topics:
- name    : joy
  topic   : joy_teleop/cmd_vel
  timeout : 0.5
  priority: 50
- name    : interactive_marker
  topic   : twist_marker_server/cmd_vel
  timeout : 0.5
  priority: 8
- name    : autonomy
  topic   : platform_control/cmd_vel
  timeout : 0.5
  priority: 50
- name    : external
  topic   : cmd_vel
  timeout : 0.5
  priority: 1
- name    : "Navigation"
  topic   : "input/navi"
  timeout:     1.0
  priority:    50
locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0    
  priority: 255
