<?xml version="1.0"?>
<robot name="sensor_asus_xtion_pro" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find roch_description)/urdf/roch_gazebo.urdf.xacro"/>
  <xacro:include filename="$(find roch_description)/urdf/roch_properties.urdf.xacro"/>
  
  <!-- Xacro properties -->
  <xacro:property name="M_SCALE" value="0.001"/>
  <xacro:property name="asus_xtion_pro_cam_py" value="0.0205"/>
  <xacro:property name="asus_xtion_pro_depth_rel_rgb_py" value="0.025" />
  <xacro:property name="asus_xtion_pro_cam_rel_rgb_py"   value="0.025" />
  <xacro:property name="asus_xiotn_cam_stack_offsety" value="-0.025"/>
  <xacro:property name="asus_xiotn_cam_stack_offsetz" value="0.025"/>

  <!-- Parameterised in part by the values in turtlebot_properties.urdf.xacro -->
  <xacro:macro name="sensor_asus_xtion_pro" params="parent">
    <joint name="camera_rgb_joint" type="fixed">
      <origin xyz="${asus_xtion_px} ${asus_xtion_py} ${asus_xtion_pz} "
              rpy="${asus_xtion_or} ${asus_xtion_op} ${asus_xtion_oy}"/>
      <parent link="${parent}"/>
      <child link="camera_rgb_frame" />
    </joint>
    <link name="camera_rgb_frame"/>

    <joint name="camera_rgb_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="camera_rgb_frame" />
      <child link="camera_rgb_optical_frame" />
    </joint>
    <link name="camera_rgb_optical_frame"/>

    <joint name="camera_joint" type="fixed">
      <origin xyz="0 ${asus_xtion_pro_cam_rel_rgb_py} 0" 
              rpy="0 0 0"/>
      <parent link="camera_rgb_frame"/>
      <child link="camera_link"/>
    </joint>
    <link name="camera_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://roch_description/meshes/sensors/xtion_pro_camera.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
        <box size="0.0730 0.2760 0.0720"/>
      </geometry>
      </collision>
      <inertial>
        <mass value="0.170" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001152600" ixy="0.0" ixz="0.0"
                 iyy="0.000148934" iyz="0.0"
                 izz="0.001154654" />
      </inertial>
    </link>

    <joint name="camera_depth_joint" type="fixed">
      <origin xyz="0 ${asus_xtion_pro_depth_rel_rgb_py} 0" rpy="0 0 0" />
      <parent link="camera_rgb_frame" />
      <child link="camera_depth_frame" />
    </joint>
    <link name="camera_depth_frame"/>

    <joint name="camera_depth_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="camera_depth_frame" />
      <child link="camera_depth_optical_frame" />
    </joint>
    <link name="camera_depth_optical_frame"/>

    <!-- RGBD sensor for simulation, same as Kinect -->
    <roch_sim_3dsensor/>


    <!-- Asus mount -->
    <joint name="mount_asus_xtion_pro_joint" type="fixed">
      <origin xyz="${asus_xtion_px} ${asus_xtion_py-asus_xiotn_cam_stack_offsety} ${asus_xtion_pz-asus_xiotn_cam_stack_offsetz}" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child link="mount_asus_xtion_pro_link"/>
    </joint>  
    <link name="mount_asus_xtion_pro_link">
      <visual>
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 0"/>
        <geometry>
          <mesh filename="package://roch_description/meshes/sensors/xtion_pro_stack.dae"/>
        </geometry>
      </visual>  
      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
        <box size="0.0330 0.2760 0.0120"/>
      </geometry>
      </collision>
      <inertial>
        <mass value="0.170" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001152600" ixy="0.0" ixz="0.0"
                 iyy="0.000148934" iyz="0.0"
                 izz="0.001154654" />
      </inertial>
    </link>
  </xacro:macro>
</robot>
